# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: stage1
    displayName: Stage1
    jobs:
      - job: Dockerbuild
        displayName: Dockerbuild
        pool:
         vmImage: $(vmImage)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'vault'
              repository: 'angular_app_test'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'


          
